remove publishing of package

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -39,45 +39,43 @@ test:
 #  only:
 #    - master
 
-pub-dev:
-  stage: publish
-  script:
-    - who
-    # - |
-    #   if [ -z "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" ]; then
-    #     echo "Missing PUB_DEV_PUBLISH_ACCESS_TOKEN environment variable"
-    #     exit 1
-    #   fi
+# pub-dev:
+#   stage: publish
+#   script:
+#     - |
+#       if [ -z "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" ]; then
+#         echo "Missing PUB_DEV_PUBLISH_ACCESS_TOKEN environment variable"
+#         exit 1
+#       fi
 
-    #   if [ -z "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" ]; then
-    #     echo "Missing PUB_DEV_PUBLISH_REFRESH_TOKEN environment variable"
-    #     exit 1
-    #   fi
+#       if [ -z "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" ]; then
+#         echo "Missing PUB_DEV_PUBLISH_REFRESH_TOKEN environment variable"
+#         exit 1
+#       fi
 
-    #   if [ -z "${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}" ]; then
-    #     echo "Missing PUB_DEV_PUBLISH_TOKEN_ENDPOINT environment variable"
-    #     exit 1
-    #   fi
+#       if [ -z "${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}" ]; then
+#         echo "Missing PUB_DEV_PUBLISH_TOKEN_ENDPOINT environment variable"
+#         exit 1
+#       fi
 
-    #   if [ -z "${PUB_DEV_PUBLISH_EXPIRATION}" ]; then
-    #     echo "Missing PUB_DEV_PUBLISH_EXPIRATION environment variable"
-    #     exit 1
-    #   fi
+#       if [ -z "${PUB_DEV_PUBLISH_EXPIRATION}" ]; then
+#         echo "Missing PUB_DEV_PUBLISH_EXPIRATION environment variable"
+#         exit 1
+#       fi
 
-    #   cat <<EOF > ~/.pub-cache/credentials.json
-    #   {
-    #     "accessToken":"$(echo "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" | base64 -d)",
-    #     "refreshToken":"$(echo "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" | base64 -d)",
-    #     "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
-    #     "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
-    #     "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
-    #   }
-    #   EOF
-    - less ~/.pub-cache/credentials.json
-    #- pub get
-    #- pub publish -f
-  only:
-    - master
+#       cat <<EOF > ~/.pub-cache/credentials.json
+#       {
+#         "accessToken":"$(echo "${PUB_DEV_PUBLISH_ACCESS_TOKEN}" | base64 -d)",
+#         "refreshToken":"$(echo "${PUB_DEV_PUBLISH_REFRESH_TOKEN}" | base64 -d)",
+#         "tokenEndpoint":"${PUB_DEV_PUBLISH_TOKEN_ENDPOINT}",
+#         "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
+#         "expiration":${PUB_DEV_PUBLISH_EXPIRATION}
+#       }
+#       EOF
+#     - pub get
+#     - pub publish -f
+#   only:
+#     - master
 
 #tag:
 #  image: docker:stable
